# Generated by Django 6.1 on 2026-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('fuel_type', models.CharField(db_index=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=80, null=True)),
                ('starting_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('coming_soon', 'Coming Soon'), ('discontinued', 'Discontinued')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='vehicles_ve_name_69bda5_idx'), models.Index(fields=['category'], name='vehicles_ve_categor_d515be_idx'), models.Index(fields=['fuel_type'], name='vehicles_ve_fuel_ty_37bc20_idx'), models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'), models.Index(fields=['starting_price'], name='vehicles_ve_startin_9b7b69_idx')],
            },
        ),
    ]
