# Generated by Django 6.1 on 2026-08-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.CharField(blank=True, max_length=80, null=True)),
                ('torque', models.CharField(blank=True, max_length=80, null=True)),
                ('mileage', models.CharField(blank=True, max_length=80, null=True)),
                ('battery_capacity', models.CharField(blank=True, max_length=80, null=True)),
                ('range_km', models.CharField(blank=True, max_length=80, null=True)),
                ('transmission', models.CharField(blank=True, max_length=80, null=True)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('boot_space', models.CharField(blank=True, max_length=80, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Variant',
                'verbose_name_plural': 'Vehicle Variants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['vehicle', 'name'], name='vehicles_ve_vehicle_12d835_idx'), models.Index(fields=['price'], name='vehicles_ve_price_782b33_idx')],
            },
        ),
    ]
