# Generated by Django 6.1 on 2026-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('connector_type', models.CharField(max_length=100)),
                ('charging_speed', models.CharField(blank=True, max_length=80, null=True)),
                ('availability', models.CharField(default='available', max_length=20)),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
    ]
