# Generated by Django 6.1 on 2026-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('usage', models.CharField(blank=True, max_length=50, null=True)),
                ('passengers', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
